[package]
name = "lite-xmr-stratum"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lite-xmr-core = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
rustls = { workspace = true }
tokio-rustls = { workspace = true }
webpki-roots = { workspace = true }
rustls-pemfile = { workspace = true }
tokio-socks = { workspace = true }
